import { toFieldName } from './utils'

export type SqlDialect = 'mysql' | 'oracle' | 'sqlite'

function quoteCol(dialect: SqlDialect, name: string): string {
  if (dialect === 'mysql') return '`' + name + '`'
  return name
}

function sqlType(dialect: SqlDialect, val: any): string {
  if (val === null || val === undefined) return 'TEXT'

  switch (dialect) {
    case 'mysql': {
      if (typeof val === 'string') return val.length > 255 ? 'TEXT' : 'VARCHAR(255)'
      if (typeof val === 'number') return Number.isInteger(val) ? 'INT' : 'DOUBLE'
      if (typeof val === 'boolean') return 'TINYINT(1)'
      if (Array.isArray(val) || typeof val === 'object') return 'JSON'
      return 'TEXT'
    }
    case 'oracle': {
      if (typeof val === 'string') return val.length > 255 ? 'CLOB' : 'VARCHAR2(255)'
      if (typeof val === 'number') return Number.isInteger(val) ? 'NUMBER(10)' : 'FLOAT'
      if (typeof val === 'boolean') return 'NUMBER(1)'
      if (Array.isArray(val) || typeof val === 'object') return 'CLOB'
      return 'CLOB'
    }
    case 'sqlite': {
      if (typeof val === 'string') return 'TEXT'
      if (typeof val === 'number') return Number.isInteger(val) ? 'INTEGER' : 'REAL'
      if (typeof val === 'boolean') return 'INTEGER'
      if (Array.isArray(val) || typeof val === 'object') return 'TEXT'
      return 'TEXT'
    }
  }
}

function primaryKey(dialect: SqlDialect): string {
  switch (dialect) {
    case 'mysql': return 'id INT AUTO_INCREMENT PRIMARY KEY'
    case 'oracle': return 'id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    case 'sqlite': return 'id INTEGER PRIMARY KEY AUTOINCREMENT'
  }
}

export function generateSQL(obj: any, rootName: string, dialect: SqlDialect = 'mysql'): string {
  const tableName = toFieldName(rootName).toLowerCase()
  const lines: string[] = []

  const sample = Array.isArray(obj) ? (obj.length > 0 ? obj[0] : null) : obj
  if (!sample || typeof sample !== 'object') {
    return `-- Cannot generate CREATE TABLE from provided JSON`
  }

  const entries = Object.entries(sample) as [string, any][]

  lines.push(`CREATE TABLE ${tableName} (`)
  lines.push(`    ${primaryKey(dialect)},`)

  const dataEntries = entries.filter(([key]) => key.toLowerCase() !== 'id')

  for (let i = 0; i < dataEntries.length; i++) {
    const [key, val] = dataEntries[i]
    const col = quoteCol(dialect, toFieldName(key).toLowerCase())
    const isLast = i === dataEntries.length - 1
    const type = sqlType(dialect, val)
    const nullable = val === null ? '' : ' NOT NULL'
    lines.push(`    ${col} ${type}${nullable}${isLast ? '' : ','}`)
  }

  lines.push(');')
  lines.push('')

  const hasNested = entries.some(([, v]) => v !== null && typeof v === 'object')
  if (hasNested) {
    lines.push('-- Note: Some fields are objects/arrays and stored as TEXT/JSON.')
    lines.push('-- Consider creating separate related tables for normalized design.')
  }

  return lines.join('\n')
}
